<?php

namespace App\Services;

class ChecklistGenerationTextService
{
    public function normalizeLanguage(?string $language): string
    {
        $language = strtolower(trim((string) $language));

        return match ($language) {
            'en', 'en-us', 'en-gb' => 'en',
            default => 'fr',
        };
    }

    public function text(string $language, string $key, array $replace = []): string
    {
        $language = $this->normalizeLanguage($language);

        $messages = [
            'fr' => [
                'agent_error_empty' => "L’agent de checklist n’a pas pu construire d’éléments à partir des checklists réutilisables ou des cas générés.",
                'draft_base_reuse' => 'Brouillon basé sur la réutilisation',
                'draft_message' => "Le brouillon de checklist a été généré par l’agent et attend la validation du testeur.",
                'generated_only' => 'réutilisation seule',
                'decision_reason_reused' => "Des éléments approuvés ont été réutilisés avant l’ajout des cas générés.",
                'decision_reason_generated' => "Aucune checklist approuvée n’était assez proche ; le brouillon a donc été généré à partir de la story.",
                'decision_explanation_default' => "L’agent a sélectionné la meilleure stratégie disponible après analyse du contexte projet, de la couverture et des zones de risque manquantes.",
                'description_generated_from' => "Générée par l’agent de checklist depuis la User Story : :title",
                'description_generator' => 'Générateur : :generator',
                'description_reuse_decision' => 'Décision de réutilisation : :action',
                'description_reuse_score' => 'Meilleur score de réutilisation : :score',
                'description_generated_at' => 'Générée le : :timestamp',
                'description_label' => 'Description :',
                'acceptance_criteria_label' => 'Critères d’acceptation :',
                'name_adapted' => 'Checklist QA adaptée',
                'name_generated' => 'Checklist QA générée',
                'covers_label' => 'Couvre :',
                'expected_result_label' => 'Résultat attendu :',
                'fallback_generator_name' => 'Fallback (base de règles)',
            ],
            'en' => [
                'agent_error_empty' => 'The checklist agent could not build items from reused checklists or generated cases.',
                'draft_base_reuse' => 'Reuse-based draft',
                'draft_message' => 'The checklist draft was generated by the agent and is waiting for tester validation.',
                'generated_only' => 'reuse-only',
                'decision_reason_reused' => 'Approved items were reused before adding generated cases.',
                'decision_reason_generated' => 'No approved checklist was close enough, so the draft was generated directly from the story.',
                'decision_explanation_default' => 'The agent selected the best available strategy after analyzing project context, coverage, and missing risk areas.',
                'description_generated_from' => 'Generated by the checklist agent from user story: :title',
                'description_generator' => 'Generator: :generator',
                'description_reuse_decision' => 'Reuse decision: :action',
                'description_reuse_score' => 'Best reuse score: :score',
                'description_generated_at' => 'Generated at: :timestamp',
                'description_label' => 'Description:',
                'acceptance_criteria_label' => 'Acceptance criteria:',
                'name_adapted' => 'Adapted QA checklist',
                'name_generated' => 'Generated QA checklist',
                'covers_label' => 'Covers:',
                'expected_result_label' => 'Expected result:',
                'fallback_generator_name' => 'Fallback (rule-based)',
            ],
        ];

        $message = $messages[$language][$key] ?? $messages['fr'][$key] ?? $key;

        foreach ($replace as $name => $value) {
            $message = str_replace(':' . $name, (string) $value, $message);
        }

        return $message;
    }

    public function localizeCase(array $testCase, string $language): array
    {
        $language = $this->normalizeLanguage($language);

        return [
            ...$testCase,
            'name' => $this->localizeCaseName((string) ($testCase['name'] ?? ''), $language),
            'description' => $this->localizeBodyText((string) ($testCase['description'] ?? ''), $language),
            'expected_result' => $this->localizeBodyText((string) ($testCase['expected_result'] ?? ''), $language),
            'category' => $this->localizeBodyText((string) ($testCase['category'] ?? ''), $language),
            'covers' => array_values(array_filter(array_map(
                fn ($cover) => $this->localizeBodyText((string) $cover, $language),
                $testCase['covers'] ?? []
            ))),
        ];
    }

    public function localizeChecklistText(?string $text, string $language): string
    {
        return $this->localizeBodyText((string) ($text ?? ''), $this->normalizeLanguage($language));
    }

    public function localizeCaseName(string $name, string $language): string
    {
        $name = $this->repairMojibake(trim($name));
        $name = preg_replace('/^(crit[eè]re|criterion)\s*\d+\s*:\s*/iu', '', $name) ?? $name;
        $name = preg_replace('/^tc[-\s]*\d+\s*[:\-]\s*/iu', '', $name) ?? $name;
        $name = preg_replace('/^gap\s*\d+\s*[-:]\s*/iu', '', $name) ?? $name;

        return trim($this->localizeBodyText($name, $language));
    }

    private function localizeBodyText(string $text, string $language): string
    {
        $text = $this->repairMojibake($text);
        $text = trim($text);

        if ($text === '') {
            return '';
        }

        return $language === 'en'
            ? $this->translateFrenchToEnglish($text)
            : $this->polishFrench($text);
    }

    private function repairMojibake(string $text): string
    {
        return strtr($text, [
            'Ã©' => 'é',
            'Ã¨' => 'è',
            'Ãª' => 'ê',
            'Ã ' => 'à',
            'Ã¢' => 'â',
            'Ã®' => 'î',
            'Ã´' => 'ô',
            'Ã¹' => 'ù',
            'Ã»' => 'û',
            'Ã§' => 'ç',
            'â€™' => '’',
            'â€“' => '–',
            'â€”' => '—',
            'â€œ' => '“',
            'â€' => '”',
            'Â' => '',
        ]);
    }

    private function polishFrench(string $text): string
    {
        $text = strtr($text, [
            'Checklists associees' => 'Checklists associées',
            'checklists associees' => 'checklists associées',
            'Generee' => 'Générée',
            'generee' => 'générée',
            'Generateur' => 'Générateur',
            'Generatrice' => 'Génératrice',
            'Decision' => 'Décision',
            'Critere' => 'Critère',
            'Critères' => 'Critères',
            'adaptee' => 'adaptée',
            'adaptees' => 'adaptées',
            'generee' => 'générée',
            'reutilisation' => 'réutilisation',
            'Reutilisation' => 'Réutilisation',
            'Resultat' => 'Résultat',
            'resultat' => 'résultat',
            'Regles' => 'Règles',
            'regles' => 'règles',
            'metier' => 'métier',
            'securite' => 'sécurité',
            'Securite' => 'Sécurité',
            'Integrite' => 'Intégrité',
            'integrite' => 'intégrité',
            'donnees' => 'données',
            'Donnees' => 'Données',
            'echec' => 'échec',
            'Echec' => 'Échec',
            'coherente' => 'cohérente',
            'coherentes' => 'cohérentes',
            'coherent' => 'cohérent',
            'coherents' => 'cohérents',
            'apres' => 'après',
            'reussi' => 'réussi',
            'reussie' => 'réussie',
            'reussit' => 'réussit',
            'succes' => 'succès',
            'etre' => 'être',
            'tache' => 'tâche',
            'taches' => 'tâches',
            'precise' => 'précise',
            'precises' => 'précises',
            'premature' => 'prématuré',
            'prematuree' => 'prématurée',
            'comprehensible' => 'compréhensible',
            'comprehensibles' => 'compréhensibles',
            'a ete' => 'a été',
            'n a' => 'n’a',
            'd abord' => 'd’abord',
            'eléments' => 'éléments',
            'elements' => 'éléments',
            'a partir' => 'à partir',
            'ete' => 'été',
            'cree' => 'créé',
            'creee' => 'créée',
            'crees' => 'créés',
            'cree.' => 'créé.',
            'creee.' => 'créée.',
            'libere' => 'libéré',
            'deja' => 'déjà',
            'echouent' => 'échouent',
            'acces' => 'accès',
            'integre' => 'intègre',
            'Integre' => 'Intègre',
            'maj' => 'mise à jour',
        ]);

        $replacements = [
            "/\\bVerifier\\b/u" => 'Vérifier',
            "/\\bverifier\\b/u" => 'vérifier',
            "/\\bLe systeme\\b/u" => 'Le système',
            "/\\ble systeme\\b/u" => 'le système',
            "/\\bL utilisateur\\b/u" => 'L’utilisateur',
            "/\\bl utilisateur\\b/u" => 'l’utilisateur',
            "/\\bAucune checklist approuvee n etait assez proche ; le brouillon a donc ete genere a partir de la story\\.\\b/u" => "Aucune checklist approuvée n’était assez proche ; le brouillon a donc été généré à partir de la story.",
            "/\\bLe flux metier principal\\b/u" => 'Le flux métier principal',
            "/\\bLa regle metier\\b/u" => 'La règle métier',
            "/\\bLe scenario\\b/u" => 'Le scénario',
            "/\\bUn double clic\\b/u" => 'Un double clic',
        ];

        foreach ($replacements as $pattern => $replacement) {
            $text = preg_replace($pattern, $replacement, $text) ?? $text;
        }

        return $text;
    }

    private function translateFrenchToEnglish(string $text): string
    {
        $exact = [
            'Le critere est respecte.' => 'The criterion is satisfied.',
            'Le critère est respecté.' => 'The criterion is satisfied.',
            'Le flux metier principal se termine correctement et la confirmation attendue est affichee.' => 'The main business flow completes successfully and displays the expected confirmation.',
            'Le flux métier principal se termine correctement et la confirmation attendue est affichée.' => 'The main business flow completes successfully and displays the expected confirmation.',
            'Les regles metier sont appliquees de facon coherente et les actions non autorisees sont bloquees.' => 'Business rules are applied consistently and unauthorized actions are blocked.',
            'Les règles métier sont appliquées de façon cohérente et unauthorized actions are blocked.' => 'Business rules are applied consistently and unauthorized actions are blocked.',
            'Les operations sensibles restent protegees et aucune information confidentielle n est exposee.' => 'Sensitive operations remain protected and no confidential information is exposed.',
            'Seules les donnees attendues sont modifiees et aucun etat incoherent ou doublon n est cree.' => 'Only the expected data is changed and no inconsistent state or duplicate record is created.',
            'L utilisateur comprend clairement ce qui s est passe et la prochaine action a effectuer.' => 'The user clearly understands what happened and what to do next.',
            'L action n est appliquee qu une seule fois et les doublons sont bloques ou ignores proprement.' => 'The action is applied only once and duplicate submissions are blocked or safely ignored.',
            'Les integrations externes reussissent avec des donnees valides et echouent sans effet de bord critique.' => 'External integrations succeed with valid data and fail without critical side effects.',
            'Le rappel est envoye une seule fois au bon destinataire avec un contenu complet et exact.' => 'The reminder is sent once to the correct recipient with complete and accurate content.',
            'Aucun rappel n est envoye et le rendez-vous conserve un etat coherent.' => 'No reminder is sent and the appointment remains in a consistent state.',
            'The behavior remains consistent, explicit, and testable for this coverage gap.' => 'The behavior remains consistent, explicit, and testable for this coverage gap.',
        ];

        if (isset($exact[$text])) {
            return $exact[$text];
        }

        $patterns = [
            '/^Cas nominal reussi pour (.+)$/u' => 'Successful happy path for $1',
            '/^Validation des champs pour (.+)$/u' => 'Input validation for $1',
            '/^Regles metier appliquees pour (.+)$/u' => 'Business rules enforced for $1',
            '/^Gestion des erreurs pour (.+)$/u' => 'Error handling for $1',
            '/^Notifications correctes pour (.+)$/u' => 'Notifications sent correctly for $1',
            '/^Integrite des donnees preservee pour (.+)$/u' => 'Data integrity preserved for $1',
            '/^Securite des donnees sensibles pour (.+)$/u' => 'Sensitive data stays protected for $1',
            '/^Retours utilisateur clairs pour (.+)$/u' => 'Clear user feedback for $1',
            '/^Prevention des actions en double pour (.+)$/u' => 'Duplicate actions are prevented for $1',
            '/^Integrations externes fiables pour (.+)$/u' => 'External integrations are reliable for $1',
            '/^Notification de rappel unique et complete pour (.+)$/u' => 'Complete single reminder notification for $1',
            '/^Regle metier respectee - (.+)$/u' => 'Business rule covered for $1',
            '/^Scenario specifique couvre - (.+)$/u' => 'Scenario-specific coverage for $1',
            '/^Notification coherente apres succes pour (.+)$/u' => 'Consistent notification after success for $1',
            '/^Notification de rappel coherente pour (.+)$/u' => 'Consistent reminder notification for $1',
            '/^Echec integration externe recupere pour (.+)$/u' => 'External integration failure handled for $1',
            '/^Carte expiree refuse le paiement$/u' => 'Expired card is rejected',
            '/^CVV invalide bloque la transaction$/u' => 'Invalid CVV blocks the transaction',
            '/^Double soumission ne cree pas de paiement en doublon$/u' => 'Duplicate submission does not create duplicate payment',
            '/^Refus du prestataire conserve un etat recuperable$/u' => 'Provider rejection keeps the flow recoverable',
            '/^Rendez-vous deja annule non annulable une seconde fois$/u' => 'Already canceled appointment cannot be canceled again',
            '/^Annulation libere de nouveau le creneau$/u' => 'Cancellation makes the slot available again',
            '/^Rendez-vous passe non annulable$/u' => 'Past appointment cannot be canceled',
            '/^Aucun rappel envoye pour un rendez-vous annule avant l echeance$/u' => 'No reminder is sent for an appointment canceled before the due time',
            '/^Contenu du rappel inclut date et instructions d acces$/u' => 'Reminder content includes date and access instructions',
            '/^Echec du canal de contact journalise sans changer le rendez-vous$/u' => 'Contact-channel failure is logged without changing the appointment',
            '/^Confirmation d annulation met a jour le statut et le creneau$/u' => 'Cancellation confirmation updates the status and slot',
            '/^Rappel envoye au bon moment avec les bonnes informations$/u' => 'Reminder is sent at the right time with the right information',
        ];

        foreach ($patterns as $pattern => $replacement) {
            if (preg_match($pattern, $text) === 1) {
                return preg_replace($pattern, $replacement, $text) ?? $text;
            }
        }

        $text = strtr($text, [
            'Vérifier qu’' => 'Verify that ',
            'Verifier qu ' => 'Verify that ',
            'Verifier qu' => 'Verify that ',
            'Vérifier que ' => 'Verify that ',
            'Verifier que ' => 'Verify that ',
            'Le systeme' => 'The system',
            'Le système' => 'The system',
            'Le rappel' => 'The reminder',
            'L utilisateur' => 'The user',
            'L’utilisateur' => 'The user',
            'Aucune' => 'No',
            'Aucun' => 'No',
            'Les donnees' => 'The data',
            'Les données' => 'The data',
            'Le rendez-vous' => 'The appointment',
            'rendez-vous' => 'appointment',
            'creneau' => 'slot',
            'créneau' => 'slot',
            'annulation' => 'cancellation',
            'paiement' => 'payment',
            'commande' => 'order',
            'recu' => 'receipt',
            'recu.' => 'receipt.',
            'coherent' => 'consistent',
            'coherente' => 'consistent',
            'bloque' => 'blocks',
            'bloquee' => 'blocked',
            'bloquées' => 'blocked',
            'refuse' => 'rejected',
            'refusee' => 'rejected',
            'rejetees' => 'rejected',
            'donnees invalides' => 'invalid data',
            'message clair' => 'clear message',
            'une seule fois' => 'only once',
            'donnees' => 'data',
            'succès confirme' => 'confirmed success',
            'succes confirme' => 'confirmed success',
            'integrations externes' => 'external integrations',
            'effet de bord' => 'side effect',
            'journalise' => 'logged',
            'journalisée' => 'logged',
            'etat' => 'state',
            'cohérent' => 'consistent',
            'cohérente' => 'consistent',
            'visible comme disponible' => 'visible as available',
        ]);

        return $text;
    }
}
