<?php

namespace App\Services;

use App\Models\Checklist;
use App\Models\ChecklistItem;
use App\Models\UserStory;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ChecklistGenerationAgentService
{
    public function __construct(
        private ChecklistRecommendationService $recommendations,
        private TestCaseGenerationService $testCaseGenerator
    ) {
    }

    public function generateDraftForUserStory(UserStory $userStory): array
    {
        $recommendations = $this->recommendations->suggestForUserStory($userStory, 3);
        $generation = $this->testCaseGenerator->generateTestCasesForUserStory($userStory);

        return DB::transaction(function () use ($userStory, $recommendations, $generation) {
            $reusableItems = $this->collectReusableItems($recommendations);
            $generatedItems = $this->normalizeGeneratedCases($generation['test_cases']);
            $mergedItems = $this->mergeItems($reusableItems, $generatedItems);

            $checklist = Checklist::create([
                'name' => "Agent Draft: {$userStory->title}",
                'description' => $this->buildChecklistDescription($userStory, $generation['generator_name'], $recommendations),
                'category' => 'agent-generated',
                'is_active' => true,
                'created_by' => Auth::id(),
                'template_scope' => 'global',
                'lifecycle_status' => 'draft',
                'generated_from' => 'ai',
                'source_user_story_id' => $userStory->id,
            ]);

            foreach ($mergedItems as $index => $item) {
                ChecklistItem::create([
                    'checklist_id' => $checklist->id,
                    'title' => $item['title'],
                    'description' => $item['description'],
                    'priority' => $item['priority'],
                    'criticality' => $item['criticality'],
                    'order' => $index + 1,
                ]);
            }

            return [
                'message' => 'Checklist draft generated by agent and is pending chef validation',
                'decision' => $this->buildDecision($recommendations, $reusableItems, $generatedItems),
                'reuse_summary' => [
                    'reused_items' => count($reusableItems),
                    'generated_items' => count($generatedItems),
                    'final_items' => count($mergedItems),
                    'source_checklists' => collect($reusableItems)
                        ->pluck('source_checklist_name')
                        ->filter()
                        ->unique()
                        ->values()
                        ->all(),
                ],
                'checklist' => $checklist->load('items'),
                'pending_validation' => true,
                'suggestions' => $recommendations,
                'generation_provider' => $generation['generator_name'],
                'generation_warnings' => $generation['fallback_errors'] ?? [],
                'available_generators' => $this->testCaseGenerator->getAvailableGenerators(),
            ];
        });
    }

    private function collectReusableItems(array $recommendations): array
    {
        $suggestionIds = collect($recommendations['suggestions'] ?? [])
            ->where('score', '>=', 30)
            ->pluck('id')
            ->take(2)
            ->values();

        if ($suggestionIds->isEmpty()) {
            return [];
        }

        return Checklist::query()
            ->with(['items' => fn ($query) => $query->orderBy('order')])
            ->whereIn('id', $suggestionIds)
            ->get()
            ->flatMap(function (Checklist $checklist) {
                return $checklist->items->map(fn (ChecklistItem $item) => [
                    'title' => $item->title,
                    'description' => $item->description ?? '',
                    'priority' => $this->normalizePriority($item->priority),
                    'criticality' => $this->normalizeCriticality($item->criticality),
                    'source' => 'reused',
                    'source_checklist_id' => $checklist->id,
                    'source_checklist_name' => $checklist->name,
                ]);
            })
            ->values()
            ->all();
    }

    private function normalizeGeneratedCases(array $testCases): array
    {
        return collect($testCases)
            ->map(fn (array $testCase, int $index) => [
                'title' => trim((string) ($testCase['name'] ?? 'Test Case ' . ($index + 1))),
                'description' => $this->buildGeneratedItemDescription($testCase),
                'priority' => $this->severityToPriority($testCase['severity'] ?? 'medium'),
                'criticality' => $this->severityToCriticality($testCase['severity'] ?? 'medium'),
                'source' => 'generated',
                'source_checklist_id' => null,
                'source_checklist_name' => null,
            ])
            ->filter(fn (array $item) => $item['title'] !== '')
            ->values()
            ->all();
    }

    private function mergeItems(array $reusableItems, array $generatedItems): array
    {
        return Collection::make([...$reusableItems, ...$generatedItems])
            ->unique(fn (array $item) => $this->fingerprint($item['title']))
            ->take(12)
            ->values()
            ->all();
    }

    private function buildDecision(array $recommendations, array $reusableItems, array $generatedItems): array
    {
        $recommendedAction = $recommendations['summary']['recommended_action'] ?? 'create_new_draft';

        return [
            'recommended_action' => $recommendedAction,
            'strategy' => count($reusableItems) > 0 ? 'reuse_then_generate_gaps' : 'generate_new_draft',
            'best_score' => $recommendations['summary']['best_score'] ?? 0,
            'reason' => count($reusableItems) > 0
                ? 'Approved checklist items were reused before generated cases were added.'
                : 'No approved checklist was similar enough, so the draft was generated from the story.',
            'generated_cases' => count($generatedItems),
        ];
    }

    private function buildChecklistDescription(UserStory $userStory, string $generatorName, array $recommendations): string
    {
        $action = $recommendations['summary']['recommended_action'] ?? 'GENERATE_NEW';
        $score = $recommendations['summary']['best_score'] ?? 0;

        return <<<DESC
Generated by checklist agent from User Story: {$userStory->title}
Generator: {$generatorName}
Reuse decision: {$action}
Best reuse score: {$score}
Generated At: {$this->getCurrentTimestamp()}

Description:
{$userStory->description}

Acceptance Criteria:
{$userStory->acceptance_criteria}
DESC;
    }

    private function buildGeneratedItemDescription(array $testCase): string
    {
        $description = trim((string) ($testCase['description'] ?? ''));
        $expected = trim((string) ($testCase['expected_result'] ?? ''));

        if ($expected === '') {
            return $description;
        }

        return trim($description . "\n\nExpected result: " . $expected);
    }

    private function fingerprint(string $value): string
    {
        $normalized = strtolower($value);
        return preg_replace('/[^a-z0-9]+/', '', $normalized) ?: $normalized;
    }

    private function normalizePriority(?string $priority): string
    {
        return in_array($priority, ['Low', 'Medium', 'High'], true) ? $priority : 'Medium';
    }

    private function normalizeCriticality(?string $criticality): string
    {
        return in_array($criticality, ['Minor', 'Major', 'Critical'], true) ? $criticality : 'Major';
    }

    private function severityToPriority(string $severity): string
    {
        return match (strtolower($severity)) {
            'critical', 'high' => 'High',
            'low' => 'Low',
            default => 'Medium',
        };
    }

    private function severityToCriticality(string $severity): string
    {
        return match (strtolower($severity)) {
            'critical', 'high' => 'Critical',
            'low' => 'Minor',
            default => 'Major',
        };
    }

    private function getCurrentTimestamp(): string
    {
        return now()->format('Y-m-d H:i:s');
    }
}
